async def blue_4(robot):
    '''What's on sale? mission'''
    await robot.drive.straight(630)
    await robot.drive.turn(-130)
    await robot.drive.straight(230)
    await robot.drive.straight(-130)
    await robot.drive.turn(90)
    await robot.drive.straight(350)
    await robot.drive.turn(-45)
    await robot.drive.straight(110)
    await robot.drive.turn(40)
    await robot.drive.straight(-260)
    await robot.drive.straight(150)
    await robot.drive.turn(-80)
    await robot.arm_run_angle(speed=700, rotation_angle=-400)
    await robot.arm_run_angle(speed=700, rotation_angle=400)
    await robot.drive.straight(-200)
    await robot.drive.turn(-90)
    await robot.drive.straight(1000)